production:
  host: 127.0.0.1
  port: 9011
  pid_file: log/ferret.pid
# development:
#   host: 127.0.0.1
#   port: 9010
#   pid_file: log/ferret.pid
# test:
#   host: localhost
#   port: 9010
#   pid_file: log/ferret.pid
